name: push_build
run-name: ${{ github.actor }} is building the project
on: [push]
jobs:
  build_project:
    runs-on: ubuntu-latest
    steps:
      - run: cd rpg-buddy
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npx next build
